# Generated by Django 5.1.7 on 2025-04-21 09:12

import ckeditor.fields
import ckeditor_uploader.fields
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_cover",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                max_length=255,
                null=True,
                upload_to="course/cover",
                variations={
                    "thumb_1080x608": (1080, 608),
                    "thumb_108x61": (108, 61, True),
                    "thumb_540x304": (540, 304),
                },
                verbose_name="封面图片",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="详情介绍"
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="remark",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="", null=True, verbose_name="分类描述"
            ),
        ),
        migrations.AlterField(
            model_name="coursechapter",
            name="summary",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="章节介绍"
            ),
        ),
        migrations.AlterField(
            model_name="coursedirection",
            name="remark",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="", null=True, verbose_name="方向描述"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="avatar",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                null=True,
                upload_to="teacher",
                variations={
                    "thumb_400x400": (400, 400),
                    "thumb_50x50": (50, 50, True),
                    "thumb_800x800": (800, 800),
                },
                verbose_name="讲师头像",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="brief",
            field=ckeditor.fields.RichTextField(
                max_length=1024, verbose_name="讲师描述"
            ),
        ),
    ]
