# Generated by Django 5.1.7 on 2025-04-25 06:29

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_course_cover_alter_course_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 4, 25, 6, 29, 36, 90701, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 4, 25, 6, 29, 36, 90701, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="活动介绍"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注信息"),
                ),
            ],
            options={
                "verbose_name": "优惠活动",
                "verbose_name_plural": "优惠活动",
                "db_table": "ol_activity",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "condition",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="设置享受优惠的价格条件,如果不填或0则没有优惠门槛",
                        verbose_name="满足优惠的条件",
                    ),
                ),
                (
                    "sale",
                    models.TextField(
                        help_text="\n    0表示免费；<br>\n    *号开头表示折扣价，例如填写*0.82,则表示八二折；<br>\n    -号开头表示减免价, 例如填写-100,则表示减免100；<br>",
                        verbose_name="优惠公式",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠公式",
                "verbose_name_plural": "优惠公式",
                "db_table": "ol_discount",
            },
        ),
        migrations.CreateModel(
            name="DiscountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="备注信息"
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠类型",
                "verbose_name_plural": "优惠类型",
                "db_table": "ol_discount_type",
            },
        ),
        migrations.CreateModel(
            name="CourseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="courses.activity",
                        verbose_name="活动",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list",
                        to="courses.discount",
                        verbose_name="优惠",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程参与活动的价格表",
                "verbose_name_plural": "课程参与活动的价格表",
                "db_table": "ol_course_activity_price",
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_type",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_list",
                to="courses.discounttype",
                verbose_name="优惠类型",
            ),
        ),
    ]
