# Generated by Django 5.1.7 on 2025-04-28 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_activity_discount_discounttype_courseactivity_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseActivity",
            new_name="CourseActivityPrice",
        ),
        migrations.AlterField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 28, 10, 46, 14, 944296),
                verbose_name="结束时间",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 28, 10, 46, 14, 944296),
                verbose_name="开始时间",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.SmallIntegerField(
                choices=[(0, "实战课程"), (1, "会员专享"), (2, "学位课程")],
                default=0,
                verbose_name="付费类型",
            ),
        ),
    ]
