# Generated by Django 5.1.7 on 2025-04-28 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_rename_courseactivity_courseactivityprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="开始时间"
            ),
        ),
    ]
