# Generated by Django 5.1.7 on 2025-04-30 15:50

import django_oss_storage.backends
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_activity_end_time_alter_activity_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_cover",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                max_length=255,
                null=True,
                storage=django_oss_storage.backends.OssMediaStorage(),
                upload_to="course/cover",
                variations={
                    "thumb_1080x608": (1080, 608),
                    "thumb_108x61": (108, 61, True),
                    "thumb_540x304": (540, 304),
                },
                verbose_name="封面图片",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="avatar",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                null=True,
                storage=django_oss_storage.backends.OssMediaStorage(),
                upload_to="teacher",
                variations={
                    "thumb_400x400": (400, 400),
                    "thumb_50x50": (50, 50, True),
                    "thumb_800x800": (800, 800),
                },
                verbose_name="讲师头像",
            ),
        ),
    ]
