# Generated by Django 5.1.7 on 2025-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_course_course_cover_alter_teacher_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credit",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="积分"
            ),
        ),
    ]
