# Generated by Django 5.1.7 on 2025-05-05 10:40

import django_oss_storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_video",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django_oss_storage.backends.OssMediaStorage(),
                upload_to="course/video",
                verbose_name="课程视频",
            ),
        ),
    ]
