# Generated by Django 5.1.7 on 2025-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(max_length=500, verbose_name="链接地址"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="note",
            field=models.CharField(max_length=150, verbose_name="备注信息"),
        ),
    ]
