# Generated by Django 5.1.7 on 2025-04-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.SmallIntegerField(
                choices=[(0, "未支付"), (1, "已支付"), (2, "已取消"), (3, "超时取消")],
                default=0,
                verbose_name="订单状态",
            ),
        ),
    ]
