# Generated by Django 5.1.7 on 2025-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="credit",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="积分"
            ),
        ),
    ]
