# Generated by Django 5.1.7 on 2025-04-25 06:29

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="avatar/%Y",
                variations={"thumb_400x400": (400, 400), "thumb_50x50": (50, 50, True)},
                verbose_name="个人头像",
            ),
        ),
    ]
