# Generated by Django 5.1.7 on 2025-05-04 18:00

import django.db.models.deletion
import django_oss_storage.backends
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_credit"),
        ("users", "0004_alter_user_avatar_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="study_time",
            field=models.IntegerField(default=0, verbose_name="总学习时长"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=stdimage.models.StdImageField(
                blank=True,
                default="avatar/2025/avatar.jpg",
                force_min_size=False,
                null=True,
                storage=django_oss_storage.backends.OssMediaStorage(),
                upload_to="avatar/%Y",
                variations={"thumb_400x400": (400, 400), "thumb_50x50": (50, 50, True)},
                verbose_name="个人头像",
            ),
        ),
        migrations.AlterModelTable(
            name="credit",
            table="ol_credit",
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("study_time", models.IntegerField(default=0, verbose_name="学习时长")),
                (
                    "chapter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_chapter",
                        to="courses.coursechapter",
                        verbose_name="章节信息",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_users",
                        to="courses.course",
                        verbose_name="课程名称",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lesson",
                        to="courses.courselesson",
                        verbose_name="课时信息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户课程购买记录",
                "verbose_name_plural": "用户课程购买记录",
                "db_table": "ol_user_course",
            },
        ),
    ]
