# Generated by Django 5.1.7 on 2025-05-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_credit"),
        ("users", "0005_user_study_time_alter_user_avatar_alter_credit_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercourse",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chapter",
                to="courses.coursechapter",
                verbose_name="章节信息",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_lesson",
                to="courses.courselesson",
                verbose_name="课时信息",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="study_time",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="学习时长"
            ),
        ),
    ]
