# Generated by Django 5.1.7 on 2025-05-07 15:30

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_course_video"),
        ("users", "0006_alter_usercourse_chapter_alter_usercourse_lesson_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank="", default="", verbose_name="练习代码"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_code",
                        to="courses.coursechapter",
                        verbose_name="章节信息",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_code",
                        to="courses.course",
                        verbose_name="课程名称",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_code",
                        to="courses.courselesson",
                        verbose_name="课时信息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码记录",
                "verbose_name_plural": "代码记录",
                "db_table": "ol_study_code",
            },
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="名称"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="序号")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank="", default="", verbose_name="笔记内容"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_note",
                        to="courses.coursechapter",
                        verbose_name="章节信息",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_note",
                        to="courses.course",
                        verbose_name="课程名称",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_note",
                        to="courses.courselesson",
                        verbose_name="课时信息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_note",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习笔记",
                "verbose_name_plural": "学习笔记",
                "db_table": "ol_study_note",
            },
        ),
        migrations.CreateModel(
            name="StudyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_time", models.IntegerField(default=0, verbose_name="学习时长")),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_progress",
                        to="courses.courselesson",
                        verbose_name="课时信息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "课时进度记录",
                "verbose_name_plural": "课时进度记录",
                "db_table": "ol_study_progress",
            },
        ),
        migrations.CreateModel(
            name="StudyQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank="", default="", verbose_name="问题"
                    ),
                ),
                (
                    "answer",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank="", default="", verbose_name="回答"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_qa",
                        to="courses.coursechapter",
                        verbose_name="章节信息",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_qa",
                        to="courses.course",
                        verbose_name="课程名称",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="to_qa",
                        to="courses.courselesson",
                        verbose_name="课时信息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_qa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "问答记录",
                "verbose_name_plural": "问答记录",
                "db_table": "ol_study_qa",
            },
        ),
    ]
